### ISSUE TITLE
Replace getHours(), getMinutes(), adding 0 and all that with `new Date().toLocaleTimeString()`

### ISSUE THREAD

**Issue by theophinetheodore** [Shibin-b/clock#3]
[Documentation on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString)

you could use 'en-US' as locale, and pass in options to options object. (i add hour12: false to remove the AM/PM stuff)

For reference, you could maybe look into my noob code: [https://github.com/TheoIsDumb/TheoOS/blob/master/src/lib/components/Date.svelte](https://github.com/TheoIsDumb/TheoOS/blob/master/src/lib/components/Date.svelte)

**Comment by shibinbevin** [comment]
i never knew about such a method, thanks for the help :)

**Comment by theophinetheodore** [comment]
you're welcome, sir!

**Comment by theophinetheodore** [comment]
btw, wen next "project"?
maybe you could redo the same thing in react or something (top-down approach)

or i would say, jump straight into a framework and learn javascript along the way. athaavumbo you get to program declaratively instead of imperatively. (bottom-up approach) i guess that's the better option. because, no one uses .innerHTML and .textContent to set values anymore.

Imperative:
```
  let heading = document.querySelector('h1')
  let value = 1

  heading.textContent = value // would have to use setInterval to update value
```

Declarative:
```
<script>
  let count = 1
 </script>

<h1>{count}</h1>
```

just go into a framework and learn that framework and javascript as you go along.

**Comment by theophinetheodore** [comment]
if you gonna jump into react, don't use create-react-app. just go for vite. vite is fast.

allenki go for a metaframework like nextjs. nextjs is basically react + routing + backend stuff + api endpoints and all that, basically in a single package. (like sveltekit or remix) athaavumbo oru vedikk pakshi. hehe
